### ISSUE TITLE
Issue in Inserting and removing node

### ISSUE THREAD

**Issue by sambhavjain9138** [ashikvarma11/tree-traverse#17]
In the current code, we are using the same state variable to store the value of insert key input and delete key input. So if you insert a key and then without adding any value in remove test box, you click on remove button, the inserted node would be removed. So i recommend using different values for both. I would like to resolve the following issue.

**Comment by ashikvarma11** [comment]
@sambhavjain9138 Good catch! You can wok on this. Go ahead, change it and create a PR. 💯
