### ISSUE TITLE
Add Linting options

### ISSUE THREAD

**Issue by ashikvarma11** [ashikvarma11/tree-traverse#19]
The project is growing fast. It would be great to add `eslint` dependencies in `package.json` file so that the code looks cleaner. Or should we use something like `prettier`? Comment down below.

**Comment by tsturtz** [comment]
Use prettier. Full stop. 😄

**Comment by tsturtz** [comment]
Check this PR #21 which installs prettier and has some suggestions regarding prettier (mostly just regurgitating their docs).
