### ISSUE TITLE
Add a better Logo

### ISSUE THREAD

**Issue by ashikvarma11** [ashikvarma11/tree-traverse#20]
Currently, we use a simple text in the place of the logo. It would be great to have a simple logo (SVG) to go in the top left corner as well as the `favicon`. This is open for discussion. Comment ideas or images that similar to your idea of the logo. Better to be a minimal one.

**Comment by omriattiya** [comment]
Hi, I can do it, but in order for your repo to participate in hacktoberfest you need to add it's label to the repo itself

**Comment by ashikvarma11** [comment]
> Hi, I can do it, but in order for your repo to participate in hacktoberfest you need to add it's label to the repo itself

Check the repo again. I have added it.

**Comment by omriattiya** [comment]
May I change the logo as well as other UI improvements?

**Comment by ashikvarma11** [comment]
@omriattiya  That would be great. Mention #4 also while creating the PR.

**Comment by ashikvarma11** [comment]
Merged with PR #22
