### ISSUE TITLE
Improve UI design

### ISSUE THREAD

**Issue by ashikvarma11** [ashikvarma11/tree-traverse#4]
The current design is quite bland. I guess we could redesign the whole page with some good color palette.
**Don't use any libraries. Just use basic CSS styling** 
- Create a separate .css file
- Change primary colors.
- Add new responsive UI.
- Add a new design layout.

**Comment by Eduardo-Vieira** [comment]
I requested a pull request for this issue

**Comment by ashikvarma11** [comment]
@Eduardo-Vieira  Thanks. I'll review the design. Right now, I'm working on CI/CD. There are a couple of changes in folder structure. You must take an update. I'll mention you in the comments when its done.

**Comment by ashikvarma11** [comment]
@Eduardo-Vieira  Please take the latest update
